In [5]:
import numpy as np
import pandas as pd

In [27]:
temp_df = pd.read_csv('/content/Review.csv')

In [28]:
df = temp_df.iloc[:10000]

In [29]:
df

     sentiment                                             review
0     Negative  I had no background knowledge of this movie be...
1     Negative  I am a huge Jane Austen fan and I ordered the ...
2     Negative  Nothing to say but Wow! Has anyone actually ha...
3     Negative  i like Jane Austin novels. I love Pride and Pr...
4     Negative  In this day and age of incredible special movi...
...        ...                                                ...
9995  Positive  I first saw this movie back in the early'90's ...
9996  Positive  NYC, 2022: The Greenhouse effect, vanished oce...
9997  Positive  Those individuals familiar with Asian cinema, ...
9998  Positive  The kids, aged 7 to 14, got such a huge kick o...
9999  Positive  I so love this movie! The animation is great (...

[10000 rows x 2 columns]

In [30]:
df['review'][1]

"I am a huge Jane Austen fan and I ordered the movie from Amazon.UK just so I could see it without waiting forever for it to come to the U.S. I really should have saved my money. What is with Anne running after Wentworth? The whole point of Anne Elliot's character is that she was quiet and refined. She is not impulsive and vulgar. And Mary, was she suffering from a stroke or something? Her speech wasn't normal, nor was her walking normal. There was no chemistry between the two main characters which made their whole 'romance' completely unbelievable. In the final scene they even have Sally Hawkins wearing the same dress Amanda Root wore during the letter scene. The same clothes do not make it the same movie. In my opinion they didn't watch the 1995 version, which even though it had it's flaws, it did stay pretty close to the book. The book, I don't even think they read it. This is kind of like a Cliff's Notes movie of Persuasion. Hit on all the high points without explaining anything.'"

In [31]:
df['sentiment'].value_counts()

sentiment
Negative    5081
Positive    4919
Name: count, dtype: int64

In [32]:
df.isnull().sum()

sentiment    0
review       0
dtype: int64

In [33]:
df.describe()

       sentiment                                             review
count      10000                                              10000
unique         2                                               9990
top     Negative  This show comes up with interesting locations ...
freq        5081                                                  3

In [34]:
df.duplicated().sum()

np.int64(10)

In [35]:
df.drop_duplicates(inplace =True)

/tmp/ipykernel_486/1154324544.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace =True)

In [36]:
import re
def raw_tags(raw_text):
  text = re.sub(re.compile('<.*?>'),'',raw_text)
  return text

In [37]:
df['review'] = df['review'].apply(raw_tags)

/tmp/ipykernel_486/983842577.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(raw_tags)

In [38]:
df['review'] = df['review'].apply(lambda x:x.lower())

/tmp/ipykernel_486/740760900.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())

In [40]:
import nltk

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [41]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

/tmp/ipykernel_486/2826946130.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [48]:
df

     sentiment                                             review
0     Negative  background knowledge movie bought it, sounded ...
1     Negative  huge jane austen fan ordered movie amazon.uk c...
2     Negative  nothing say wow! anyone actually somebody snea...
3     Negative  like jane austin novels. love pride prejudice ...
4     Negative  day age incredible special movie effects, one ...
...        ...                                                ...
9995  Positive  first saw movie back early'90's first released...
9996  Positive  nyc, 2022: greenhouse effect, vanished oceans,...
9997  Positive  individuals familiar asian cinema, whole, awar...
9998  Positive  kids, aged 7 14, got huge kick film gave copy ...
9999  Positive  love movie! animation great (for pokã©mon movi...

[9990 rows x 2 columns]

In [60]:

X = df.iloc[:,1:2]
y = df['sentiment']

In [61]:
X

                                                 review
0     background knowledge movie bought it, sounded ...
1     huge jane austen fan ordered movie amazon.uk c...
2     nothing say wow! anyone actually somebody snea...
3     like jane austin novels. love pride prejudice ...
4     day age incredible special movie effects, one ...
...                                                 ...
9995  first saw movie back early'90's first released...
9996  nyc, 2022: greenhouse effect, vanished oceans,...
9997  individuals familiar asian cinema, whole, awar...
9998  kids, aged 7 14, got huge kick film gave copy ...
9999  love movie! animation great (for pokã©mon movi...

[9990 rows x 1 columns]

In [62]:
y

0       Negative
1       Negative
2       Negative
3       Negative
4       Negative
          ...
9995    Positive
9996    Positive
9997    Positive
9998    Positive
9999    Positive
Name: sentiment, Length: 9990, dtype: object

In [63]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [64]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [65]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [66]:
X_train.shape

(7992, 1)

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [67]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [68]:
X_train_bow.shape

(7992, 47413)

In [69]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [70]:

y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6496496496496497

In [71]:
confusion_matrix(y_test,y_pred)

array([[731, 297],
       [403, 567]])

In [72]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8388388388388388

In [73]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8358358358358359

In [75]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

In [76]:

X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [77]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8308308308308309